const tickerLibrary = [
    // --- GROWTH (Technologie, High-Growth, Innovative SaaS) ---
    { yf: "NVDA", name: "NVIDIA Corp", index: "NASDAQ / S&P 500", group: "Growth", sector: "Semis", cur: "USD" },
    { yf: "AAPL", name: "Apple Inc", index: "NASDAQ / Dow", group: "Growth", sector: "Tech", cur: "USD" },
    { yf: "MSFT", name: "Microsoft Corp", index: "NASDAQ / Dow", group: "Growth", sector: "Software", cur: "USD" },
    { yf: "AMZN", name: "Amazon.com Inc", index: "NASDAQ / S&P 500", group: "Growth", sector: "Consumer Discretionary", cur: "USD" },
    { yf: "GOOGL", name: "Alphabet Inc (Google)", index: "NASDAQ / S&P 500", group: "Growth", sector: "Communication", cur: "USD" },
    { yf: "META", name: "Meta Platforms", index: "NASDAQ / S&P 500", group: "Growth", sector: "AdTech", cur: "USD" },
    { yf: "TSLA", name: "Tesla Inc", index: "NASDAQ / S&P 500", group: "Growth", sector: "Automotive", cur: "USD" },
    { yf: "NFLX", name: "Netflix Inc", index: "NASDAQ / S&P 500", group: "Growth", sector: "Media", cur: "USD" },
    { yf: "AMD", name: "Advanced Micro Devices", index: "NASDAQ / S&P 500", group: "Growth", sector: "Semis", cur: "USD" },
    { yf: "PLTR", name: "Palantir Technologies", index: "S&P 500", group: "Growth", sector: "Software", cur: "USD" },
    { yf: "CRWD", name: "CrowdStrike Holdings", index: "NASDAQ", group: "Growth", sector: "Software", cur: "USD" },
    { yf: "SNOW", name: "Snowflake Inc", index: "NYSE", group: "Growth", sector: "Software", cur: "USD" },
    { yf: "SHOP", name: "Shopify Inc", index: "NYSE", group: "Growth", sector: "Software", cur: "USD" },
    { yf: "MELI", name: "MercadoLibre Inc", index: "NASDAQ", group: "Growth", sector: "Platform", cur: "USD" },
    { yf: "NOW", name: "ServiceNow Inc", index: "S&P 500", group: "Growth", sector: "Software", cur: "USD" },
    { yf: "ADBE", name: "Adobe Inc", index: "NASDAQ / S&P 500", group: "Growth", sector: "Software", cur: "USD" },
    { yf: "ARM", name: "Arm Holdings plc", index: "NASDAQ", group: "Growth", sector: "Semis", cur: "USD" },
    { yf: "SMCI", name: "Super Micro Computer", index: "NASDAQ", group: "Growth", sector: "AI Infra", cur: "USD" },
    { yf: "ONON", name: "On Holding AG", index: "NYSE", group: "Growth", sector: "Apparel", cur: "USD" },
    { yf: "SE", name: "Sea Limited", index: "NYSE", group: "Growth", sector: "Platform", cur: "USD" },
    { yf: "ZTS", name: "Zoetis Inc", index: "S&P 500", group: "Growth", sector: "Animal Health", cur: "USD" },
    { yf: "ISRG", name: "Intuitive Surgical", index: "S&P 500", group: "Growth", sector: "MedTech", cur: "USD" },
    { yf: "UBER", name: "Uber Technologies", index: "S&P 500", group: "Growth", sector: "Platform", cur: "USD" },
    { yf: "ABNB", name: "Airbnb Inc", index: "S&P 500", group: "Growth", sector: "Travel", cur: "USD" },
    { yf: "DASH", name: "DoorDash Inc", index: "S&P 500", group: "Growth", sector: "Platform", cur: "USD" },

    // --- DEFENSIVE (Gesundheit, Basiskonsumgüter, Versorger) ---
    { yf: "JNJ", name: "Johnson & Johnson", index: "Dow Jones / S&P 500", group: "Defensive", sector: "Pharma", cur: "USD" },
    { yf: "PG", name: "Procter & Gamble", index: "Dow Jones / S&P 500", group: "Defensive", sector: "Staples", cur: "USD" },
    { yf: "KO", name: "Coca-Cola Co", index: "Dow Jones / S&P 500", group: "Defensive", sector: "Staples", cur: "USD" },
    { yf: "PEP", name: "PepsiCo Inc", index: "S&P 500", group: "Defensive", sector: "Staples", cur: "USD" },
    { yf: "WMT", name: "Walmart Inc", index: "Dow Jones / S&P 500", group: "Defensive", sector: "Retail", cur: "USD" },
    { yf: "COST", name: "Costco Wholesale", index: "S&P 500", group: "Defensive", sector: "Retail", cur: "USD" },
    { yf: "MCD", name: "McDonald's Corp", index: "Dow Jones / S&P 500", group: "Defensive", sector: "Restaurant", cur: "USD" },
    { yf: "ABT", name: "Abbott Laboratories", index: "S&P 500", group: "Defensive", sector: "MedTech", cur: "USD" },
    { yf: "LLY", name: "Eli Lilly & Co", index: "S&P 500", group: "Defensive", sector: "Pharma", cur: "USD" },
    { yf: "UNH", name: "UnitedHealth Group", index: "Dow Jones / S&P 500", group: "Defensive", sector: "Health Ins", cur: "USD" },
    { yf: "PFE", name: "Pfizer Inc", index: "S&P 500", group: "Defensive", sector: "Pharma", cur: "USD" },
    { yf: "MRK", name: "Merck & Co", index: "Dow Jones / S&P 500", group: "Defensive", sector: "Pharma", cur: "USD" },
    { yf: "RWE.DE", name: "RWE AG", index: "DAX", group: "Defensive", sector: "Utilities", cur: "EUR" },
    { yf: "EOAN.DE", name: "E.ON SE", index: "DAX", group: "Defensive", sector: "Utilities", cur: "EUR" },
    { yf: "ENGI.PA", name: "Engie SA", index: "Eurostoxx 50", group: "Defensive", sector: "Utilities", cur: "EUR" },
    { yf: "NESN.SW", name: "Nestlé SA", index: "SMI / Euro", group: "Defensive", sector: "Staples", cur: "CHF" },
    { yf: "NOVN.SW", name: "Novartis AG", index: "SMI / Euro", group: "Defensive", sector: "Pharma", cur: "CHF" },
    { yf: "ROG.SW", name: "Roche Holding", index: "SMI / Euro", group: "Defensive", sector: "Pharma", cur: "CHF" },

    // --- CYCLICAL (Industrie, Automobil, Rohstoffe, Finanzen) ---
    { yf: "CAT", name: "Caterpillar Inc", index: "Dow Jones / S&P 500", group: "Cyclical", sector: "Industrials", cur: "USD" },
    { yf: "DE", name: "Deere & Co", index: "S&P 500", group: "Cyclical", sector: "Industrials", cur: "USD" },
    { yf: "HON", name: "Honeywell International", index: "Dow Jones / S&P 500", group: "Cyclical", sector: "Industrials", cur: "USD" },
    { yf: "BA", name: "Boeing Co", index: "Dow Jones / S&P 500", group: "Cyclical", sector: "Aerospace", cur: "USD" },
    { yf: "GE", name: "GE Aerospace", index: "S&P 500", group: "Cyclical", sector: "Aerospace", cur: "USD" },
    { yf: "JPM", name: "JPMorgan Chase & Co", index: "Dow Jones / S&P 500", group: "Cyclical", sector: "Financials", cur: "USD" },
    { yf: "BAC", name: "Bank of America", index: "S&P 500", group: "Cyclical", sector: "Financials", cur: "USD" },
    { yf: "GS", name: "Goldman Sachs Group", index: "Dow Jones / S&P 500", group: "Cyclical", sector: "Financials", cur: "USD" },
    { yf: "V", name: "Visa Inc", index: "Dow Jones / S&P 500", group: "Cyclical", sector: "Financials", cur: "USD" },
    { yf: "MA", name: "Mastercard Inc", index: "S&P 500", group: "Cyclical", sector: "Financials", cur: "USD" },
    { yf: "XOM", name: "Exxon Mobil Corp", index: "Dow Jones / S&P 500", group: "Cyclical", sector: "Energy", cur: "USD" },
    { yf: "CVX", name: "Chevron Corp", index: "Dow Jones / S&P 500", group: "Cyclical", sector: "Energy", cur: "USD" },
    { yf: "BMW.DE", name: "BMW AG", index: "DAX", group: "Cyclical", sector: "Automotive", cur: "EUR" },
    { yf: "MBG.DE", name: "Mercedes-Benz Group", index: "DAX", group: "Cyclical", sector: "Automotive", cur: "EUR" },
    { yf: "VOW3.DE", name: "Volkswagen AG", index: "DAX", group: "Cyclical", sector: "Automotive", cur: "EUR" },
    { yf: "BAS.DE", name: "BASF SE", index: "DAX", group: "Cyclical", sector: "Materials", cur: "EUR" },
    { yf: "SIE.DE", name: "Siemens AG", index: "DAX", group: "Cyclical", sector: "Industrials", cur: "EUR" },
    { yf: "AIR.PA", name: "Airbus SE", index: "Eurostoxx 50", group: "Cyclical", sector: "Aerospace", cur: "EUR" },
    { yf: "SAN.MC", name: "Banco Santander", index: "Eurostoxx 50", group: "Cyclical", sector: "Financials", cur: "EUR" },
    { yf: "AR", name: "Antero Resources", index: "S&P 500", group: "Cyclical", sector: "Energy", cur: "USD" },
    { yf: "DVN", name: "Devon Energy", index: "S&P 500", group: "Cyclical", sector: "Energy", cur: "USD" },

    // --- SENSITIVE (Halbleiter, Software, Medien, Telekommunikation) ---
    { yf: "AVGO", name: "Broadcom Inc", index: "S&P 500", group: "Sensitive", sector: "Semis", cur: "USD" },
    { yf: "QCOM", name: "Qualcomm Inc", index: "S&P 500", group: "Sensitive", sector: "Semis", cur: "USD" },
    { yf: "INTC", name: "Intel Corp", index: "Dow Jones / S&P 500", group: "Sensitive", sector: "Semis", cur: "USD" },
    { yf: "CSCO", name: "Cisco Systems", index: "Dow Jones / S&P 500", group: "Sensitive", sector: "Tech", cur: "USD" },
    { yf: "IBM", name: "International Business Machines", index: "Dow Jones / S&P 500", group: "Sensitive", sector: "Tech", cur: "USD" },
    { yf: "ORCL", name: "Oracle Corp", index: "S&P 500", group: "Sensitive", sector: "Software", cur: "USD" },
    { yf: "CRM", name: "Salesforce Inc", index: "Dow Jones / S&P 500", group: "Sensitive", sector: "Software", cur: "USD" },
    { yf: "DIS", name: "Walt Disney Co", index: "Dow Jones / S&P 500", group: "Sensitive", sector: "Media", cur: "USD" },
    { yf: "CMCSA", name: "Comcast Corp", index: "S&P 500", group: "Sensitive", sector: "Media", cur: "USD" },
    { yf: "T", name: "AT&T Inc", index: "S&P 500", group: "Sensitive", sector: "Communication", cur: "USD" },
    { yf: "VZ", name: "Verizon Communications", index: "Dow Jones / S&P 500", group: "Sensitive", sector: "Communication", cur: "USD" },
    { yf: "SAP.DE", name: "SAP SE", index: "DAX / Eurostoxx 50", group: "Sensitive", sector: "Software", cur: "EUR" },
    { yf: "IFX.DE", name: "Infineon Technologies", index: "DAX", group: "Sensitive", sector: "Semis", cur: "EUR" },
    { yf: "DTE.DE", name: "Deutsche Telekom", index: "DAX", group: "Sensitive", sector: "Communication", cur: "EUR" },
    { yf: "ASML.AS", name: "ASML Holding", index: "Eurostoxx 50", group: "Sensitive", sector: "Semis", cur: "EUR" },
    { yf: "ADYEN.AS", name: "Adyen N.V.", index: "Eurostoxx 50", group: "Sensitive", sector: "Fintech", cur: "EUR" },

    // --- HIGH YIELD & VALUE (Dividenden, REITs, Midstream, Versicherungen) ---
    { yf: "O", name: "Realty Income Corp", index: "S&P 500", group: "High Yield", sector: "REIT", cur: "USD" },
    { yf: "VICI", name: "VICI Properties", index: "S&P 500", group: "High Yield", sector: "REIT", cur: "USD" },
    { yf: "ENB", name: "Enbridge Inc", index: "NYSE", group: "High Yield", sector: "Midstream", cur: "CAD" },
    { yf: "WKL.AS", name: "Wolters Kluwer", index: "Euronext", group: "High Yield", sector: "Info Svcs", cur: "EUR" },
    { yf: "MC.PA", name: "LVMH Moët Hennessy", index: "Eurostoxx 50", group: "High Yield", sector: "Luxury", cur: "EUR" },
    { yf: "ALV.DE", name: "Allianz SE", index: "DAX", group: "High Yield", sector: "Financials", cur: "EUR" },
    { yf: "MUVG.DE", name: "Munich Re", index: "DAX", group: "High Yield", sector: "Insurance", cur: "EUR" },
    { yf: "DB1.DE", name: "Deutsche Börse AG", index: "DAX", group: "High Yield", sector: "Financials", cur: "EUR" },
    { yf: "SPGI", name: "S&P Global Inc", index: "S&P 500", group: "High Yield", sector: "Info Svcs", cur: "USD" },
    { yf: "NVO", name: "Novo Nordisk", index: "NYSE / OMX", group: "High Yield", sector: "Pharma", cur: "DKK" }
];

